### ISSUE TITLE
Further work TBD debugging

### ISSUE THREAD

**Issue by vishvanath45** [Compro-Prasad/GLUG#3]
- conditional breakpoints
- watchpoints
- `Ctrl-X+A`
- Performance analysis of various sort.
- Linked List Segmentation Fault 
- info breakpoints  
- hardware breakpoints vs software breakpoints 

see more at - https://sourceware.org/gdb/onlinedocs/gdb/index.html#SEC_Contents

**Comment by Compro-Prasad** [comment]
This is also done.
